
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

mybatis:
  type-aliases-package: com.example.demo.dto